"""add_invite_expiry_to_jobs

Revision ID: 8f108d4b1a46
Revises: a0d4198d483e
Create Date: 2026-07-15 08:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f108d4b1a46'
down_revision = 'a0d4198d483e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('invite_expiry_value', sa.Integer(), nullable=False, server_default='24'))
    op.add_column('jobs', sa.Column('invite_expiry_unit', sa.String(length=50), nullable=False, server_default='hours'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'invite_expiry_unit')
    op.drop_column('jobs', 'invite_expiry_value')
    # ### end Alembic commands ###
