"""add_interview_duration_to_jobs

Revision ID: a0d4198d483e
Revises: 1c4da8e425c2
Create Date: 2026-07-13 11:08:44.286917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d4198d483e'
down_revision = '1c4da8e425c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('interview_duration', sa.Integer(), nullable=False, server_default='30'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'interview_duration')
    # ### end Alembic commands ###
