"""add_match_breakdown_and_ai_recommendation

Revision ID: bbea406c0801
Revises: b1b47d3a9c16
Create Date: 2026-07-06 12:52:55.111909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbea406c0801'
down_revision = 'b1b47d3a9c16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('match_breakdown', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('ai_recommendation', sa.String(length=100), nullable=True))
    op.create_foreign_key('fk_latest_interview', 'candidates', 'interviews', ['latest_interview_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_latest_interview', 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'ai_recommendation')
    op.drop_column('candidates', 'match_breakdown')
    # ### end Alembic commands ###
